### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by ayazmaroof** [vlacs/saml20-clj#1]
Hi, we are very interested in this project.

We are trying out your library and facing some problems. Could you please provide some working examples for reference? It will help us a lot.

**Comment by lvh** [comment]
There's an example in `dev/`: https://github.com/vlacs/saml20-clj/tree/dev/dev

**Comment by jrdoane** [comment]
@lvh is correct. It's not the best of examples, but there is on where he suggests. Just to elaborate a little bit, it's only a sample ring app that reads in a basic config file. The code for this is here: https://github.com/vlacs/saml20-clj/blob/dev/dev/user.clj#L38

The bottom of the user.clj has a function for spinning it up that takes in a path to an EDN file. There is a sample EDN file in the root of the repo here: https://github.com/vlacs/saml20-clj/blob/dev/config.dist.edn

I apologize for the state of this library. It was a "my first Clojure app" kind of thing that never ended up getting revisited.
